services:
  - type: web
    name: yourmovies-backend
    runtime: python
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: yourmovies
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        sync: false
      - key: APP_NAME
        value: yourmovies
      - key: GOOGLE_CLIENT_ID
        value: 709682814260-hmnqf2ca2jh12puead6f4j39uabef1t9.apps.googleusercontent.com
      - key: CLOUDINARY_URL
        sync: false
